before:
  hooks:
    - go get -u github.com/valyala/quicktemplate/qtc
    - qtc
builds:
  - id: aws-lambda-handler
    binary: handler
    main: ./cmd/aws/lambda/handler
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: website
    binary: website
    main: ./cmd/http
    env:
      - CGO_ENABLED=0
archives:
  - id: aws-lambda-handler
    builds:
      - aws-lambda-handler
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
